// lib/data.ts
export type Branch = 'CSE'|'ECE'|'IT'|'MECH'|'CIVIL'|'BCA'|'MCA'
export type Demand = 'Explosive'|'High'|'Growing'|'Stable'

export const BRANCHES: Branch[] = ['CSE','ECE','IT','MECH','CIVIL','BCA','MCA']
export const BRANCH_FULL: Record<Branch,string> = {
  CSE:'Computer Science', ECE:'Electronics & Comm', IT:'Information Technology',
  MECH:'Mechanical Engineering', CIVIL:'Civil Engineering', BCA:'BCA', MCA:'MCA'
}
export const BRANCH_COLOR: Record<Branch,string> = {
  CSE:'#818cf8', ECE:'#fb923c', IT:'#c084fc',
  MECH:'#fbbf24', CIVIL:'#34d399', BCA:'#f472b6', MCA:'#60a5fa'
}

export const BG_SCENES: Record<Branch, {
  bg:[number,number,number], accent:[number,number,number],
  objects:{type:string,c:[number,number,number]}[]
}> = {
  CSE:{ bg:[8,10,22], accent:[129,140,248], objects:[
    {type:'laptop',c:[129,140,248]},{type:'laptop',c:[100,110,220]},
    {type:'code',c:[99,102,241]},{type:'code',c:[129,140,248]},{type:'code',c:[80,90,200]},
    {type:'cube',c:[129,140,248]},{type:'cube',c:[99,102,241]},
    {type:'circuit',c:[60,70,180]},{type:'sphere',c:[129,140,248]},
  ]},
  ECE:{ bg:[22,8,4], accent:[251,146,60], objects:[
    {type:'chip',c:[251,146,60]},{type:'chip',c:[220,120,40]},{type:'chip',c:[251,146,60]},
    {type:'circuit',c:[251,146,60]},{type:'circuit',c:[200,100,30]},{type:'circuit',c:[251,146,60]},
    {type:'wave',c:[251,146,60]},{type:'wave',c:[220,120,40]},
    {type:'resistor',c:[251,146,60]},{type:'sphere',c:[251,146,60]},
  ]},
  IT:{ bg:[14,4,22], accent:[192,132,252], objects:[
    {type:'server',c:[192,132,252]},{type:'server',c:[160,100,220]},{type:'server',c:[192,132,252]},
    {type:'cube',c:[192,132,252]},{type:'cube',c:[160,100,220]},
    {type:'sphere',c:[192,132,252]},{type:'sphere',c:[140,80,200]},
    {type:'code',c:[192,132,252]},{type:'circuit',c:[160,100,220]},
  ]},
  MECH:{ bg:[18,10,2], accent:[251,191,36], objects:[
    {type:'gear',c:[251,191,36]},{type:'gear',c:[220,160,20]},{type:'gear',c:[251,191,36]},{type:'gear',c:[200,140,10]},
    {type:'bolt',c:[251,191,36]},{type:'bolt',c:[220,160,20]},
    {type:'cube',c:[251,191,36]},{type:'sphere',c:[251,191,36]},{type:'cad',c:[220,160,20]},
  ]},
  CIVIL:{ bg:[2,14,8], accent:[52,211,153], objects:[
    {type:'beam',c:[52,211,153]},{type:'beam',c:[30,180,120]},{type:'beam',c:[52,211,153]},
    {type:'cube',c:[52,211,153]},{type:'cube',c:[30,180,120]},{type:'cube',c:[52,211,153]},
    {type:'sphere',c:[52,211,153]},{type:'sphere',c:[30,180,120]},{type:'blueprint',c:[52,211,153]},
  ]},
  BCA:{ bg:[20,4,14], accent:[244,114,182], objects:[
    {type:'phone',c:[244,114,182]},{type:'phone',c:[200,80,150]},
    {type:'laptop',c:[244,114,182]},{type:'cube',c:[244,114,182]},
    {type:'sphere',c:[200,80,150]},{type:'sphere',c:[244,114,182]},
    {type:'code',c:[244,114,182]},{type:'circuit',c:[200,80,150]},
  ]},
  MCA:{ bg:[2,10,22], accent:[96,165,250], objects:[
    {type:'server',c:[96,165,250]},{type:'server',c:[70,130,220]},
    {type:'cube',c:[96,165,250]},{type:'cube',c:[70,130,220]},{type:'cube',c:[96,165,250]},
    {type:'code',c:[96,165,250]},{type:'code',c:[70,130,220]},
    {type:'sphere',c:[96,165,250]},{type:'circuit',c:[70,130,220]},
  ]},
}

export interface Tool {
  id:string; name:string; cat:string; cc:string; tag:string
  what:string; why:string; free:string; cert:string; certUrl:string
  salary:string; cos:string[]; br:Branch[]; demand:Demand
}

export const ALL_TOOLS: Tool[] = [
  {id:'uipath',name:'UiPath',cat:'RPA & Automation',cc:'#ea580c',tag:'The robot doing repetitive work — companies pay serious money for this',what:'Records and replays human computer actions at massive scale. The #1 RPA platform globally.',why:'TCS, Infosys, Wipro hire 15,000+ RPA developers/year. A fresher with UiPath cert bypasses the standard IT entry track entirely.',free:'UiPath Community Edition — completely free, no credit card, no expiry.',cert:'UiPath Certified Professional (Academy — free prep)',certUrl:'https://academy.uipath.com/',salary:'Rs4-8 LPA fresher -> Rs12-22 LPA (2 YOE) -> Rs35 LPA+ Architect',cos:['TCS Digital','Infosys BPM','Wipro','Accenture','Deloitte USI','EY GDS'],br:['CSE','IT','MCA','BCA'],demand:'Explosive'},
  {id:'mulesoft',name:'MuleSoft',cat:'Integration Platforms',cc:'#0891b2',tag:'Enterprise plumbing — invisible, essential, highly paid',what:'Connects enterprise systems via the Anypoint Platform. Every large company has dozens of systems that need integration.',why:'Integration is the most in-demand and least-taught skill in colleges. Every bank, telecom, and PSU runs MuleSoft.',free:'Anypoint Platform — 30-day full trial. Salesforce Trailhead has free paths.',cert:'MuleSoft Certified Developer Level 1',certUrl:'https://trailhead.salesforce.com/en/content/learn/supermocs/mulesoft-developer-mcd-level-1',salary:'Rs6-10 LPA fresher -> Rs15-25 LPA (2 YOE) -> Rs40 LPA+ Architect',cos:['Salesforce','Deloitte','Capgemini','Infosys','Standard Chartered'],br:['CSE','IT','MCA'],demand:'High'},
  {id:'bedrock',name:'Amazon Bedrock',cat:'Cloud AI / GenAI',cc:'#d97706',tag:"Call the world's best AI models with 3 lines of code",what:'Managed AWS service to call foundation AI models (Claude, Llama, Titan) via API.',why:'Every company building AI in 2025 uses Bedrock. Demand growing 40% per year.',free:'AWS Free Tier includes Bedrock API calls. AWS Builder Labs: free guided labs.',cert:'AWS Certified AI Practitioner (new 2024)',certUrl:'https://aws.amazon.com/certification/certified-ai-practitioner/',salary:'Rs10-18 LPA fresher -> Rs25-50 LPA (2 YOE)',cos:['Amazon','Accenture AWS','Wipro AWS BU','TCS AWS CoE'],br:['CSE','IT','MCA','ECE'],demand:'Explosive'},
  {id:'watson',name:'IBM Watson',cat:'Enterprise AI',cc:'#1d4ed8',tag:'The AI inside banks and government — powering regulated India',what:'Enterprise AI suite — NLP, visual recognition, and watsonx. Used in regulated industries.',why:'Banking, insurance, and government run Watson. Students here are immediately valuable at IBM, TCS iON, and every PSU.',free:'IBM Watson Lite — free forever. IBM SkillsBuild: free courses and certs.',cert:'IBM AI Engineering Professional Certificate (Coursera — audit free)',certUrl:'https://www.coursera.org/professional-certificates/ibm-applied-ai',salary:'Rs6-12 LPA fresher -> Rs18-30 LPA Watson Architect',cos:['IBM India','TCS iON','Infosys','State Bank IT','DRDO'],br:['CSE','IT','ECE','MCA'],demand:'Stable'},
  {id:'salesforce',name:'Salesforce',cat:'CRM & ERP',cc:'#0891b2',tag:"World's #1 CRM — Trailhead makes it completely free to learn",what:'Most used CRM globally. Developers build custom apps and automations on the platform.',why:'9.3 million people in the Salesforce ecosystem. Admin cert = Rs6-10 LPA as a fresher.',free:'Salesforce Trailhead — completely free, gamified. Developer Org free forever.',cert:'Salesforce Certified Administrator -> Platform Developer I',certUrl:'https://trailhead.salesforce.com/',salary:'Rs6-10 LPA Admin -> Rs10-18 LPA Developer -> Rs35 LPA+ Architect',cos:['Salesforce','Cognizant','Infosys','Capgemini','Persistent Systems'],br:['CSE','IT','BCA','MCA'],demand:'High'},
  {id:'servicenow',name:'ServiceNow',cat:'Enterprise Platforms',cc:'#15803d',tag:'Operating system for enterprise workflows — barely any college teaches it',what:'Cloud platform for IT service management, HR workflows, and enterprise automation.',why:'Growing 25% YoY with a chronic talent shortage. CSA cert gets Rs8-12 LPA as a fresher.',free:'ServiceNow Developer Instance — free personal dev environment. Now Learning: free courses.',cert:'ServiceNow Certified System Administrator (CSA)',certUrl:'https://nowlearning.servicenow.com/',salary:'Rs6-12 LPA fresher with CSA -> Rs18-35 LPA (2 YOE)',cos:['Accenture','Deloitte','Capgemini','DXC Technology','Infosys'],br:['CSE','IT','MCA'],demand:'Growing'},
  {id:'powerbi',name:'Power BI + Snowflake',cat:'Data & Analytics',cc:'#ca8a04',tag:'Turn data into decisions — every company needs it',what:'Power BI builds dashboards executives decide from. Snowflake is the leading cloud data warehouse.',why:'Every company with 50+ employees needs dashboard builders. Power BI Desktop is completely free.',free:'Power BI Desktop — free download. Snowflake — 30-day trial + $400 credits.',cert:'Microsoft PL-300: Power BI Data Analyst Associate',certUrl:'https://learn.microsoft.com/en-us/credentials/certifications/exams/pl-300/',salary:'Rs4-8 LPA fresher -> Rs12-20 LPA BI Developer (2 YOE)',cos:['Microsoft','Deloitte','PwC','KPMG','Mu Sigma'],br:['CSE','IT','MECH','CIVIL','BCA','MCA'],demand:'High'},
  {id:'boomi',name:'Dell Boomi',cat:'Integration Platforms',cc:'#0891b2',tag:'Fastest path into enterprise integration — low-code, high salary',what:'Cloud-native integration with drag-and-drop connectors. Top choice for mid-size enterprises.',why:'Easier to learn than MuleSoft with far less competition from candidates.',free:'Boomi Trial — free 30 days. Boomi Community: free learning paths.',cert:'Boomi Professional Developer Certification',certUrl:'https://community.boomi.com/s/training',salary:'Rs5-9 LPA fresher -> Rs14-22 LPA (2 YOE)',cos:['Dell Technologies','IBM','Accenture','Cognizant','Hexaware'],br:['CSE','IT','MCA'],demand:'Growing'},
  {id:'aws-iot',name:'AWS IoT Core',cat:'IoT & Edge',cc:'#ff9900',tag:'Connect physical devices to the cloud — foundation of industrial IoT',what:'AWS IoT Core connects billions of IoT devices to the cloud securely.',why:'EV, automotive, and smart manufacturing deploy IoT at scale. ECE students with AWS IoT skills walk into Bosch, Ather, and Qualcomm directly.',free:'AWS Free Tier: 250,000 messages/month free for 12 months.',cert:'AWS Certified Developer — Associate (covers IoT patterns)',certUrl:'https://aws.amazon.com/iot/',salary:'Rs5-10 LPA fresher -> Rs15-25 LPA (2 YOE)',cos:['Ather Energy','Bosch India','Qualcomm','Wipro IoT','L&T Technology'],br:['ECE'],demand:'Explosive'},
  {id:'labview',name:'NI LabVIEW',cat:'Test & Measurement',cc:'#ffd700',tag:'Industry standard for hardware testing — ISRO, DRDO, semiconductor fabs use it',what:'LabVIEW is used for automated test equipment, data acquisition, and instrument control globally.',why:'ISRO, DRDO, semiconductor fabs, and automotive test labs run LabVIEW. ECE students who know it are immediately placed in test engineering roles.',free:'NI Academic License — free for students through your college.',cert:'Certified LabVIEW Developer (CLD)',certUrl:'https://www.ni.com/en-in/support/certification.html',salary:'Rs4-8 LPA fresher -> Rs12-22 LPA Test Engineer (2 YOE)',cos:['ISRO','DRDO','Texas Instruments','Analog Devices','Honeywell'],br:['ECE'],demand:'High'},
  {id:'matlab-ece',name:'MATLAB + Simulink',cat:'Simulation & Control',cc:'#e16919',tag:'Model and simulate real systems — mandatory for ECE in automotive and telecom',what:'MATLAB handles numerical computing. Simulink enables model-based design for embedded systems and signal processing.',why:'Automotive, aerospace, and telecom companies mandate MATLAB/Simulink. ECE freshers who can model a control system stand out completely.',free:'MATLAB Online — free trial. Free academic license through most colleges.',cert:'MathWorks Certified MATLAB Associate',certUrl:'https://matlabacademy.mathworks.com/',salary:'Rs5-10 LPA fresher -> Rs14-24 LPA Controls/Signal Engineer (2 YOE)',cos:['Tata Elxsi','KPIT Technologies','Continental','Bosch','ISRO'],br:['ECE','MECH'],demand:'High'},
  {id:'fpga',name:'Xilinx Vivado (FPGA)',cat:'FPGA & VLSI',cc:'#e60000',tag:'Design custom logic — the skill that gets into semiconductor companies',what:'Xilinx Vivado is the design suite for FPGA development. Write VHDL/Verilog and synthesise into real programmable chips.',why:'Qualcomm, MediaTek, Intel, AMD need FPGA/VLSI engineers urgently. ECE students with FPGA skills are among the highest-paid freshers.',free:'Xilinx Vivado WebPACK — completely free, no license required.',cert:'Xilinx Certified FPGA Developer',certUrl:'https://www.xilinx.com/training.html',salary:'Rs8-15 LPA fresher -> Rs20-40 LPA FPGA/VLSI Engineer (2 YOE)',cos:['Qualcomm','MediaTek','Intel','AMD','NVIDIA','Samsung Semiconductor'],br:['ECE'],demand:'Explosive'},
  {id:'canalyzer',name:'Vector CANalyzer',cat:'Automotive Electronics',cc:'#ff5722',tag:'The tool inside every car — automotive ECU testing and development',what:'CANalyzer is the industry standard for CAN bus analysis, testing, and simulation in automotive electronics.',why:'With EV adoption exploding, automotive electronics engineers are in massive demand. Ather, Ola, Tata, Bosch all use CANalyzer daily.',free:'Vector CANalyzer Demo — free with limited channels. Student licenses via Vector University Program.',cert:'Vector AUTOSAR Development Certification',certUrl:'https://www.vector.com/int/en/know-how/vector-academy/',salary:'Rs6-12 LPA fresher -> Rs18-35 LPA Automotive Engineer (2 YOE)',cos:['Ather Energy','Ola Electric','Tata Motors','Bosch','Continental','KPIT'],br:['ECE'],demand:'Explosive'},
  {id:'ansys',name:'Ansys',cat:'Simulation & FEA',cc:'#ffb800',tag:'Simulation engine behind aerospace, automotive, and energy engineering',what:'Ansys is the leading engineering simulation platform — structural FEA, CFD, thermal, and electromagnetic simulations.',why:'Every aerospace, automotive, and energy company uses Ansys. MECH freshers who can run FEA or CFD have a massive advantage.',free:'Ansys Student Edition — fully free with no feature restrictions for academic use.',cert:'Ansys Certified Professional (ACP)',certUrl:'https://www.ansys.com/en-in/academic/free-student-products',salary:'Rs4-9 LPA fresher -> Rs14-28 LPA Simulation Engineer (2 YOE)',cos:['Tata Motors','Mahindra','L&T Engineering','ISRO','GE Aerospace'],br:['MECH'],demand:'High'},
  {id:'solidworks',name:'SolidWorks',cat:'CAD & Design',cc:'#e74c3c',tag:'Most-used CAD tool in product design and manufacturing',what:'SolidWorks is a parametric 3D CAD tool used for product design, assembly modelling, and engineering drawings.',why:'Every manufacturing company from Godrej to Caterpillar uses SolidWorks. A MECH fresher with a SolidWorks portfolio gets interviews others do not.',free:'SolidWorks Student Edition — free through SOLIDWORKS for Students program.',cert:'Certified SolidWorks Associate (CSWA) — free exam for students',certUrl:'https://www.solidworks.com/sw/support/mcad-certification-programs.htm',salary:'Rs3-7 LPA fresher -> Rs12-22 LPA Design Engineer (2 YOE)',cos:['Tata Motors','Mahindra Engineering','Godrej','Bosch','3M India'],br:['MECH'],demand:'High'},
  {id:'siemens-nx',name:'Siemens NX + Teamcenter',cat:'CAD & PLM',cc:'#009999',tag:'Enterprise CAD and PLM — automotive and aerospace standard',what:'Siemens NX is advanced 3D CAD/CAM/CAE. Teamcenter is the world leading PLM system.',why:'NX skills open doors to Tata Elxsi, L&T, HAL, Mahindra, and global MNCs. PLM knowledge is a rare premium skill.',free:'Siemens Learning Advantage — free student access to NX and Teamcenter online training.',cert:'Siemens NX Certified Professional',certUrl:'https://training.plm.automation.siemens.com/',salary:'Rs5-10 LPA fresher -> Rs15-30 LPA PLM/CAD Engineer (2 YOE)',cos:['Tata Elxsi','L&T Engineering','HAL','Mahindra','Boeing India'],br:['MECH'],demand:'Growing'},
  {id:'matlab-mech',name:'MATLAB + Simulink',cat:'Simulation & Control',cc:'#e16919',tag:'Model and simulate real systems — control, thermal, and manufacturing',what:'MATLAB handles numerical computing. Simulink enables model-based design of control systems and manufacturing processes.',why:'MECH roles in automotive, aerospace, and robotics universally require MATLAB.',free:'MATLAB Online — free trial. Free academic license through most colleges.',cert:'MathWorks Certified MATLAB Associate',certUrl:'https://matlabacademy.mathworks.com/',salary:'Rs5-10 LPA fresher -> Rs14-24 LPA Controls Engineer (2 YOE)',cos:['ISRO','DRDO','Tata Motors','L&T Technology','GE','Siemens India'],br:['MECH'],demand:'High'},
  {id:'revit',name:'Autodesk Revit (BIM)',cat:'BIM & Design',cc:'#0070c0',tag:'Building Information Modelling — mandatory on govt projects above Rs100 crore',what:'Revit creates intelligent 3D BIM models for architectural, structural, and MEP engineering.',why:'BIM is now mandatory on Indian government infrastructure projects above Rs100 crore. Revit skills command 20-30% salary premium.',free:'Autodesk Education — free 1-year access to Revit for students.',cert:'Autodesk Certified Professional: Revit for Structural Design',certUrl:'https://www.autodesk.com/certification/',salary:'Rs3.5-7 LPA fresher -> Rs12-22 LPA BIM Engineer (2 YOE)',cos:['L&T Construction','Shapoorji Pallonji','DLF','AECOM India','Jacobs'],br:['CIVIL'],demand:'Growing'},
  {id:'staad',name:'STAAD.Pro',cat:'Structural Analysis',cc:'#0052cc',tag:'Industry standard for structural analysis in India',what:'STAAD.Pro analyses and designs steel, concrete, and composite structures against IS, AISC, and BS codes.',why:'Every structural consultancy and construction company in India uses STAAD.Pro. CIVIL freshers who can model using IS codes are immediately employable.',free:'Bentley Student License — free through the Bentley Academic program.',cert:'Bentley Structural Analyst Certification',certUrl:'https://www.bentley.com/software/staad-pro/',salary:'Rs3.5-7 LPA fresher -> Rs10-20 LPA Structural Engineer (2 YOE)',cos:['L&T Construction','STUP Consultants','Gammon India','Afcons','AECOM'],br:['CIVIL'],demand:'Stable'},
  {id:'qgis',name:'QGIS + ArcGIS',cat:'GIS & Geospatial',cc:'#509b2a',tag:'Map and analyse anything — fastest-growing skill in infrastructure',what:'QGIS enables spatial analysis, flood mapping, land use planning, and route optimisation.',why:'Smart cities, highway projects, and urban planning now require GIS skills. ISRO, NHAI, and smart city SPVs hire GIS-proficient CIVIL engineers at premium.',free:'QGIS — completely free, open source. Free learning at qgis.org.',cert:'Esri ArcGIS Desktop Entry Certification',certUrl:'https://www.qgis.org/en/site/',salary:'Rs3-7 LPA fresher -> Rs10-18 LPA GIS Analyst (2 YOE)',cos:['NHAI','Smart City SPVs','ISRO','AECOM','Jacobs','Atkins India'],br:['CIVIL'],demand:'Growing'},
  {id:'primavera',name:'Oracle Primavera',cat:'Project Management',cc:'#c74634',tag:'Gold standard for infrastructure project scheduling',what:'Oracle Primavera P6 is the industry-leading project management software for large infrastructure projects.',why:'Every EPC company uses Primavera. A CIVIL engineer who can schedule in Primavera is immediately valuable.',free:'Oracle Primavera Cloud — 30-day free trial.',cert:'Oracle Primavera P6 Certified Implementation Specialist',certUrl:'https://education.oracle.com/oracle-primavera-p6-enterprise-project-portfolio-management/product_164',salary:'Rs3.5-7 LPA fresher -> Rs12-25 LPA Project Engineer (2 YOE)',cos:['L&T Construction','NCC Limited','Afcons','Shapoorji','RITES','IRCON'],br:['CIVIL'],demand:'Stable'},
  {id:'wordpress',name:'WordPress + Shopify',cat:'Web & eCommerce',cc:'#3858e9',tag:'Powers 40% of the internet — learn it and you are immediately hireable',what:'WordPress powers 43% of all websites. Shopify powers 10% of all ecommerce.',why:'BCA graduates who can build and customise WordPress + Shopify sites are immediately employed at agencies, startups, and as freelancers.',free:'WordPress.com — free plan. Shopify Partner account — free to develop.',cert:'Shopify Partner Academy Certification (free)',certUrl:'https://shopify.dev/docs/marketapps/certs',salary:'Rs2.5-5 LPA fresher -> Rs8-15 LPA Web Developer (2 YOE)',cos:['Digital agencies','D2C brands','startups','freelance','Dentsu India'],br:['BCA'],demand:'High'},
  {id:'ga4',name:'Google Analytics + Ads',cat:'Digital Marketing',cc:'#f4b400',tag:'Data-driven marketing — every business is desperate for this skill',what:'Google Analytics 4 tracks website traffic. Google Ads enables paid search and display advertising.',why:'Every company running a website needs analytics and ads. BCA graduates with GA4 + Google Ads certification are hired immediately.',free:'Google Analytics Demo — free. Google Ads Learning — free. Both certifications free.',cert:'Google Analytics GAIQ + Google Ads Certification (both free)',certUrl:'https://skillshop.google.com/',salary:'Rs2.5-5 LPA fresher -> Rs8-18 LPA Digital Analyst (2 YOE)',cos:['Performics','iProspect','GroupM','D2C startups','ecommerce companies'],br:['BCA'],demand:'High'},
  {id:'docker',name:'Docker Containers',cat:'DevOps & Containers',cc:'#2496ed',tag:'Pack applications as standard packages for instant deployment anywhere',what:'Docker containerizes software, grouping application code with dependencies to run consistently on any environment.',why:'Standard DevOps practice. Hiring processes require containers for React, Node, and Python apps.',free:'Docker Desktop Community Edition is free for personal use.',cert:'Docker Certified Associate (DCA)',certUrl:'https://training.mirantis.com/certification/docker-certified-associate/',salary:'Rs6-12 LPA fresher -> Rs15-25 LPA',cos:['TCS','Cognizant','Wipro','Razorpay','CRED'],br:['CSE','IT','MCA','BCA'],demand:'High'},
  {id:'kubernetes',name:'Kubernetes Orchestration',cat:'DevOps & Containers',cc:'#326ce5',tag:'Automate deployment, scaling, and operations of application containers',what:'Open-source container orchestration tool that automates deployment, scaling, and management of cloud systems.',why:'Every large tech team running microservices utilizes Kubernetes. High talent gap for freshers.',free:'Minikube and Kind are free tools to run Kubernetes clusters locally.',cert:'Certified Kubernetes Administrator (CKA)',certUrl:'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',salary:'Rs8-15 LPA fresher -> Rs20-35 LPA (2 YOE)',cos:['Google','Microsoft','Amazon India','Red Hat','Capgemini'],br:['CSE','IT','MCA'],demand:'Explosive'},
  {id:'terraform',name:'Terraform IaC',cat:'DevOps & Infrastructure',cc:'#844fba',tag:'Write code to spin up cloud infrastructure instantly and securely',what:'Infrastructure as Code tool to build, change, and version cloud infrastructure safely and efficiently.',why:'Automates AWS, Azure, and Google Cloud services. High-paying niche SDE role.',free:'HashiCorp Terraform is open-source and free to install.',cert:'HashiCorp Certified: Terraform Associate',certUrl:'https://www.hashicorp.com/certification/terraform-associate',salary:'Rs7-13 LPA fresher -> Rs18-30 LPA',cos:['HashiCorp','Deloitte Cloud','AWS India','L&T Infotech','Infosys CoE'],br:['CSE','IT','MCA'],demand:'High'},
  {id:'kafka',name:'Apache Kafka',cat:'Data Pipelines & Streaming',cc:'#000000',tag:'High-throughput distributed event streaming platform used by top apps',what:'Distributed data streaming platform capable of handling trillions of events a day.',why:'Powering real-time notifications, banking ledger streams, and logs for Uber, Netflix, and banks.',free:'Apache Kafka is open-source and free to download and run locally.',cert:'Confluent Certified Developer for Apache Kafka (CCDAK)',certUrl:'https://www.confluent.io/certification/',salary:'Rs8-16 LPA fresher -> Rs18-32 LPA',cos:['Confluent','Uber India','Paytm','PhonePe','Flipkart'],br:['CSE','IT','MCA'],demand:'High'},
  {id:'redis',name:'Redis Caching',cat:'Caching & Databases',cc:'#d82c20',tag:'Ultra-fast in-memory database used for caching and session storage',what:'In-memory data structure store used as a database, cache, and message broker.',why:'Optimizes web applications by caching database queries. High performance backend requirement.',free:'Redis Community Edition is open-source and free to install.',cert:'Redis Certified Developer',certUrl:'https://university.redis.com/certification/',salary:'Rs6-11 LPA fresher -> Rs14-22 LPA',cos:['Redis Labs','Swiggy','Zomato','Paytm','Amazon'],br:['CSE','IT','MCA','BCA'],demand:'High'},
  {id:'graphql',name:'GraphQL',cat:'Modern APIs',cc:'#e10098',tag:'Alternative to REST APIs where clients request exactly what they need',what:'Query language for APIs and runtime for fulfilling queries with existing data.',why:'Speeds up mobile and web applications by fetching only needed data. standard SDE skill.',free:'Apollo GraphQL and standard servers are free and open-source.',cert:'Apollo Graph Developer Associate (Free Certification)',certUrl:'https://www.apollographql.com/tutorials/certifications',salary:'Rs5-10 LPA fresher -> Rs12-20 LPA',cos:['Meta','Shopify','Gartner','Nagarro','Tech Mahindra'],br:['CSE','IT','MCA','BCA'],demand:'High'},
  {id:'nextjs',name:'Next.js Framework',cat:'Web Frameworks',cc:'#000000',tag:'The React framework for production with SSR, SEO, and route optimization',what:'React framework for building fast, search-engine-friendly web applications.',why:'The standard for modern web application frontend development globally.',free:'Next.js is open-source and free. Free deployments on Vercel.',cert:'Vercel Next.js Certification',certUrl:'https://vercel.com/templates/next.js',salary:'Rs6-12 LPA fresher -> Rs14-24 LPA',cos:['Vercel','Razorpay','CRED','Zepto','Meesho'],br:['CSE','IT','MCA','BCA'],demand:'Explosive'},
  {id:'fastapi',name:'FastAPI',cat:'Web Frameworks',cc:'#059669',tag:'High-performance Python API framework for microservices and AI apps',what:'Modern, fast (high-performance) web framework for building APIs with Python.',why:'Go-to framework for connecting React frontends with machine learning and GenAI backends.',free:'FastAPI is open-source and free. Highly documented.',cert:'FastAPI Professional (Python Web Academy)',certUrl:'https://fastapi.tiangolo.com/',salary:'Rs5-10 LPA fresher -> Rs12-22 LPA',cos:['Netflix','Uber','Microsoft','TCS AI CoE','startups'],br:['CSE','IT','MCA','BCA'],demand:'Growing'},
  {id:'aws-lambda',name:'AWS Lambda',cat:'Serverless Cloud',cc:'#ff9900',tag:'Run server code without managing servers. Pay only when code runs',what:'Serverless computing service that runs code in response to events automatically.',why:'Drastically reduces server costs. Used by startups and enterprises for microservices.',free:'AWS Free Tier: 1 million free requests per month forever.',cert:'AWS Certified Developer — Associate',certUrl:'https://aws.amazon.com/certification/certified-developer-associate/',salary:'Rs6-12 LPA fresher -> Rs16-26 LPA',cos:['Amazon','Accenture','Cognizant','Swiggy','Ola'],br:['CSE','IT','MCA'],demand:'High'},
  {id:'figma',name:'Figma UI/UX',cat:'UI/UX Design',cc:'#f24e1e',tag:'Collaborative interface design tool used to prototype websites & apps',what:'Web-based vector graphics editor and prototyping tool for user experience design.',why:'Every developer working on frontends needs to know how to read and build from Figma files.',free:'Figma Starter Plan is free for students and individuals.',cert:'Figma UI/UX Design Professional (Coursera/Google)',certUrl:'https://www.figma.com/education/',salary:'Rs4-8 LPA fresher -> Rs10-18 LPA Designer',cos:['Figma','Google Design','Flipkart','Zomato','Pine Labs'],br:['CSE','IT','MCA','BCA'],demand:'Growing'},
  {id:'altium',name:'Altium Designer',cat:'PCB Design',cc:'#00828a',tag:'Professional high-speed PCB design and layout tool for hardware products',what:'Industry standard software package for printed circuit board design.',why:'Semiconductor, EV, hardware startups, and IoT firms mandate Altium for circuit schematic capture.',free:'Altium Student License is free for students via educational email.',cert:'Altium Certified ECAD Professional',certUrl:'https://www.altium.com/education',salary:'Rs5-10 LPA fresher -> Rs12-22 LPA PCB Designer',cos:['Qualcomm','Intel','Ather Energy','Bosch','Qualcomm India'],br:['ECE'],demand:'High'},
  {id:'kicad',name:'KiCad EDA',cat:'PCB Design',cc:'#1f4e79',tag:'Open-source schematics and layout tool with no feature limitations',what:'Free and open-source software suite for electronic design automation (EDA).',why:'Used extensively by startups and freelancers to design custom circuit boards for free.',free:'KiCad is completely open-source and free forever.',cert:'KiCad Professional Layout Designer (KiCad Academy)',certUrl:'https://www.kicad.org/',salary:'Rs4-8 LPA fresher -> Rs10-18 LPA Hardware Engineer',cos:['Hardware startups','makerspaces','freelance agencies','DRDO'],br:['ECE'],demand:'Growing'},
  {id:'freertos',name:'FreeRTOS',cat:'Real-Time OS',cc:'#00a2e8',tag:'Market-leading real-time operating system for microcontrollers & IoT',what:'Real-time operating system kernel for embedded devices, ported to 40+ microcontrollers.',why:'Essential for writing deterministic, multi-tasking software on smart sensors and IoT hardware.',free:'FreeRTOS is open-source and free to download and use.',cert:'AWS Certified IoT Developer (covers FreeRTOS integration)',certUrl:'https://www.freertos.org/',salary:'Rs6-11 LPA fresher -> Rs15-25 LPA',cos:['Ather Energy','Bosch India','Texas Instruments','Qualcomm'],br:['ECE'],demand:'Explosive'},
  {id:'stm32',name:'STM32CubeMX',cat:'Embedded Systems',cc:'#03234b',tag:'Initialize and configure STMicroelectronics ARM Cortex-M microcontrollers',what:'Graphical tool that allows configuration of STM32 microcontrollers and generates C initialization code.',why:'ARM Cortex-M controllers dominate modern consumer electronics, medical devices, and automobiles.',free:'STM32CubeMX and STM32CubeIDE are completely free to download and use.',cert:'STMicroelectronics Microcontroller Developer Certificate',certUrl:'https://www.st.com/en/development-tools/stm32cubemx.html',salary:'Rs5-9 LPA fresher -> Rs12-20 LPA Embedded Engineer',cos:['Ather Energy','Bosch','Schneider Electric','L&T Technology Services'],br:['ECE'],demand:'High'},
  {id:'canoe',name:'Vector CANoe',cat:'Automotive Electronics',cc:'#ff5722',tag:'Simulate, test, and analyze entire automotive networks and ECUs',what:'Development and testing tool for individual ECUs and entire automotive networks.',why:'Used by major car brands (Tesla, Tata, Mahindra) to test vehicle communication systems.',free:'Demo version available. Vector University Program provides student licenses.',cert:'Vector CANoe Advanced System Tester',certUrl:'https://www.vector.com/int/en/products/products-a-z/software-tools/canoe/',salary:'Rs7-14 LPA fresher -> Rs18-35 LPA (2 YOE)',cos:['Ather Energy','Ola Electric','Tata Motors','Bosch','Continental'],br:['ECE'],demand:'Explosive'},
  {id:'cadence',name:'Cadence Virtuoso',cat:'VLSI Design',cc:'#e31b23',tag:'The gold standard for analog, custom digital, and RF IC design',what:'Platform used to design custom integrated circuits, physical layouts, and silicon chips.',why:'Silicon fabs and chip designers mandate Cadence Virtuoso. High entry barrier but massive salaries.',free:'Access via university VLSI labs under Cadence University Program.',cert:'Cadence Certified Custom IC Specialist',certUrl:'https://www.cadence.com/en_US/home/training.html',salary:'Rs9-18 LPA fresher -> Rs22-45 LPA (2 YOE)',cos:['Qualcomm','Intel','MediaTek','NVIDIA','Samsung Semiconductor'],br:['ECE'],demand:'Explosive'},
  {id:'synopsys',name:'Synopsys Design Compiler',cat:'VLSI Design',cc:'#5f259f',tag:'Synthesize RTL Verilog descriptions into optimized gate-level netlists',what:'RTL synthesis tool that optimizes designs for speed, area, and power for custom chips.',why:'Used in ASIC/VLSI flows to translate code into physical transistors on silicon.',free:'Available in college VLSI labs under Synopsys University Program.',cert:'Synopsys Certified ASIC Synthesis Engineer',certUrl:'https://www.synopsys.com/support/training.html',salary:'Rs9-18 LPA fresher -> Rs22-45 LPA ASIC Engineer',cos:['NVIDIA','Qualcomm','Intel','AMD','Broadcom'],br:['ECE'],demand:'Explosive'},
  {id:'autocad3d',name:'AutoCAD 3D',cat:'CAD & Design',cc:'#808080',tag:'Create 3D models and layout designs for manufacturing and plant piping',what:'3D modeling and design tool used in structural, mechanical, and civil drawings.',why:'Standard draftsman and modeler tool used to convert 2D blueprints into 3D objects.',free:'Autodesk Student Plan offers 1-year free license.',cert:'Autodesk Certified Professional: AutoCAD',certUrl:'https://www.autodesk.com/certification/exams/autocad-professional',salary:'Rs3-6 LPA fresher -> Rs8-14 LPA',cos:['L&T Engineering','Godrej','Tata Consulting Engineers','Afcons'],br:['MECH','CIVIL'],demand:'Stable'},
  {id:'creo',name:'PTC Creo',cat:'CAD & Design',cc:'#2c3e50',tag:'Enterprise 3D parametric CAD modeling software for product manufacturing',what:'PTC Creo handles parametric modeling, simulation, and manufacturing drawings.',why:'Used extensively in heavy machinery, automotive components, and consumer goods.',free:'PTC Creo Student Edition is free for academic use.',cert:'PTC Certified Creo Associate',certUrl:'https://www.ptc.com/en/support/training',salary:'Rs3.5-8 LPA fresher -> Rs10-18 LPA Design Engineer',cos:['Mahindra','Caterpillar','John Deere','L&T Engineering'],br:['MECH'],demand:'High'},
  {id:'fusion360',name:'Autodesk Fusion 360',cat:'CAD & CAM',cc:'#d35400',tag:'Cloud-based CAD, CAM, CAE, and 3D PCB design platform for product dev',what:'Integrated design tool linking CAD modeling directly to CNC machining (CAM).',why:'Used by startups, product design firms, and CNC shops for agile manufacturing.',free:'Autodesk Fusion 360 for students is free for 1 year.',cert:'Autodesk Certified Professional: Fusion 360 CAD/CAM',certUrl:'https://www.autodesk.com/products/fusion-360/personal',salary:'Rs3.5-7 LPA fresher -> Rs9-15 LPA',cos:['Product design startups','CNC tooling shops','Tata Elxsi','Godrej'],br:['MECH'],demand:'High'},
  {id:'fluent',name:'Ansys Fluent',cat:'Simulation & FEA',cc:'#16a085',tag:'Computational Fluid Dynamics (CFD) solver for heat & fluid flow systems',what:'Advanced CFD simulation tool modeling fluid flow, turbulence, heat transfer, and reactions.',why:'Crucial for designing EV battery thermal systems, aerodynamics of cars, and turbine cooling.',free:'Ansys Student Edition includes Ansys Fluent with limited cell count.',cert:'Ansys Certified Professional: Fluids (Fluent)',certUrl:'https://www.ansys.com/en-in/academic/free-student-products',salary:'Rs5-10 LPA fresher -> Rs14-25 LPA CFD Analyst',cos:['Tata Motors','Mahindra EV CoE','Ather Energy','ISRO','GE Aerospace'],br:['MECH'],demand:'High'},
  {id:'lsdyna',name:'Ansys LS-DYNA',cat:'Simulation & FEA',cc:'#2980b9',tag:'Explicit simulation software modeling high-speed crash tests & impact analyses',what:'Explicit solver modeling crash tests, drops, explosions, and metal stamping.',why:'Used by automotive safety groups to validate vehicle crash ratings without physical testing.',free:'Ansys Student Edition includes explicit dynamics solvers.',cert:'Ansys Certified Professional: Explicit Dynamics',certUrl:'https://www.ansys.com/en-in/academic/free-student-products',salary:'Rs5-10 LPA fresher -> Rs15-28 LPA Crash Analyst',cos:['Tata Motors','Mahindra','Maruti Suzuki','Toyota India','L&T Defence'],br:['MECH'],demand:'High'},
  {id:'catia',name:'CATIA v5/v6',cat:'CAD & Design',cc:'#8e44ad',tag:'Advanced CAD suite powering aerospace, aviation, and automotive styling',what:'High-end physical design and styling suite used in aerospace and automotive giants.',why:'Standard for Boeing, Airbus, and premium automotive styling studios.',free:'CATIA Student Edition available at discounted rates.',cert:'Dassault Systemes CATIA Associate',certUrl:'https://www.3ds.com/training/certification-program',salary:'Rs4.5-9 LPA fresher -> Rs12-22 LPA Design Engineer',cos:['Boeing India','HAL','Airbus India CoE','Tata Motors','Mahindra'],br:['MECH'],demand:'High'},
  {id:'mastercam',name:'Mastercam',cat:'CAM & CNC',cc:'#27ae60',tag:'The leading Computer-Aided Manufacturing software for CNC machining',what:'CAM software generating toolpaths for multi-axis CNC milling and lathe machines.',why:'Translates 3D CAD files into code that physical factory robots use to mill metal parts.',free:'Mastercam Demo / Home Learning Edition is free to download.',cert:'Mastercam Certified Programmer',certUrl:'https://www.mastercam.com/support/certification/',salary:'Rs3.5-7 LPA fresher -> Rs8-14 LPA CAM Programmer',cos:['Manufacturing firms','Godrej Aerospace','L&T Heavy Engineering','component exporters'],br:['MECH'],demand:'Stable'},
  {id:'civil3d',name:'AutoCAD Civil 3D',cat:'Civil Engineering',cc:'#f1c40f',tag:'Design roadways, corridor modeling, and grading for infrastructure projects',what:'Civil engineering design and documentation software for highway, land, and water design.',why:'Used by highway design firms (NHAI contractors) to plan curves, grades, and cut-and-fill.',free:'Autodesk Student Plan offers 1-year free access.',cert:'Autodesk Certified Professional: Civil 3D Infrastructure',certUrl:'https://www.autodesk.com/certification/exams/civil-3d-infrastructure',salary:'Rs3.5-7 LPA fresher -> Rs10-18 LPA Roadway Engineer',cos:['L&T Infrastructure','NHAI Contractors','AECOM','Jacobs Engineering'],br:['CIVIL'],demand:'Growing'},
  {id:'etabs',name:'Bentley ETABS',cat:'Structural Analysis',cc:'#2ecc71',tag:'Analyze and design high-rise building structures under wind and earthquake load',what:'Software package for structural analysis and design of building systems.',why:'Every multi-story residential/commercial structure designed in India uses ETABS for safety design.',free:'Bentley Student/Evaluation programs offer access.',cert:'CSI Certified ETABS Professional',certUrl:'https://www.csiamerica.com/products/etabs',salary:'Rs3.5-8 LPA fresher -> Rs12-20 LPA Structural Engineer',cos:['L&T Construction','STUP Consultants','Gammon India','Shapoorji Pallonji'],br:['CIVIL'],demand:'High'},
  {id:'tekla',name:'Tekla Structures',cat:'Structural Analysis',cc:'#3498db',tag:'Create detailed 3D structural models of steel and concrete for fabrication',what:'BIM software that allows structural steel and concrete detailers to model and draft.',why:'Used to design structural steel frames for industrial plants, refineries, and stadiums.',free:'Tekla Campus offers free student licenses and learning paths.',cert:'Trimble Certified Tekla Structures Detailer',certUrl:'https://campus.tekla.com/',salary:'Rs3.5-7.5 LPA fresher -> Rs10-18 LPA Steel Detailer',cos:['L&T Heavy Civil','Shapoorji','Steel Fabricators','Refinery Builders'],br:['CIVIL'],demand:'Growing'},
]

export interface Phase {
  n:number; nm:string; dr:string
  sk:string[]; tl:string[]; ent:string[]; ct:string[]
  role:string; sal:string
}
export interface CompanyTier { t:string; n:string; s:string }
export interface Track {
  id:string; branch:Branch; title:string
  tag:string; demand:string
  phases:Phase[]; cos:CompanyTier[]
}

export const TRACKS: Track[] = [
  { id:'fs', branch:'CSE', title:'Full-Stack Developer', tag:'Most hired role in India', demand:'85,000+ openings right now',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Python or JavaScript','HTML + CSS','Git & GitHub','Data structures'],tl:['VS Code','GitHub','Replit'],ent:[],ct:['Git & GitHub Skills (free)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['React.js + Node.js','SQL + MongoDB','REST API design','DSA -- medium'],tl:['Postman','Docker basics','Vercel'],ent:['Salesforce (Trailhead -- free)','Power BI basics'],ct:['AWS Cloud Practitioner'],role:'SDE Intern / Junior SDE',sal:'Rs4-8 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['TypeScript','AWS core services','CI/CD pipelines','System design'],tl:['GitHub Actions','AWS Console','DataDog'],ent:['MuleSoft basics','Salesforce Dev I','ServiceNow CSA'],ct:['AWS SA Associate'],role:'SDE II / Senior SDE',sal:'Rs10-20 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Advanced system design','Kubernetes + Terraform','Architecture decisions'],tl:['Kubernetes','Terraform','Grafana'],ent:['MuleSoft Certified Dev','Amazon Bedrock','Snowflake'],ct:['AWS SA Professional','CKA'],role:'Senior SDE / Tech Lead / EM',sal:'Rs25-60 LPA'},
    ],
    cos:[{t:'Dream -- Tier 1',n:'Google, Microsoft, Amazon, Adobe, Atlassian',s:'Rs20-45 LPA fresher'},{t:'High-growth startups',n:'Razorpay, CRED, Zepto, Swiggy, Meesho',s:'Rs12-25 LPA fresher'},{t:'Stable MNCs',n:'TCS Digital, Infosys, Wipro, Accenture',s:'Rs4-7 LPA fresher'}]},
  { id:'ai', branch:'CSE', title:'AI / ML Engineer', tag:'Highest-growth career in tech', demand:'40% YoY demand increase',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Python (mandatory)','Linear algebra + stats','Pandas + NumPy','Data visualisation'],tl:['Jupyter','Google Colab','Kaggle'],ent:[],ct:['Python for Everybody (free)'],role:'Building fundamentals',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Scikit-learn','TensorFlow or PyTorch','Model evaluation','Feature engineering'],tl:['Kaggle','Hugging Face','FastAPI'],ent:['IBM Watson Studio (free)','AWS SageMaker free tier'],ct:['IBM AI Engineering (free)','AWS AI Practitioner'],role:'ML Engineer / Data Scientist',sal:'Rs6-12 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['MLOps -- deploy & monitor','LLM fine-tuning','Vector databases'],tl:['AWS SageMaker','MLflow','Airflow'],ent:['Amazon Bedrock (GenAI)','IBM watsonx'],ct:['AWS ML Specialty'],role:'ML Engineer / MLOps',sal:'Rs14-28 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Foundation model architecture','AI system design','Research to production'],tl:['Amazon Bedrock','Vertex AI'],ent:['Amazon Bedrock architect','IBM watsonx enterprise'],ct:['AWS AI/ML Hero','NVIDIA DLI'],role:'Senior ML Engineer / AI Lead',sal:'Rs30-80 LPA'},
    ],
    cos:[{t:'AI-first companies',n:'Google DeepMind, OpenAI, NVIDIA, Microsoft AI',s:'Rs30-80 LPA'},{t:'Product companies',n:'Flipkart, PhonePe, Meesho, Ola, Zomato',s:'Rs15-35 LPA'},{t:'IT AI practices',n:'TCS AI Lab, Infosys Nia, Wipro HOLMES',s:'Rs8-18 LPA'}]},
  { id:'emb', branch:'ECE', title:'Embedded & IoT Engineer', tag:'Hardware-software bridge -- EV, robotics, smart devices', demand:'EV sector creating 50,000+ embedded roles by 2026',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['C programming (mandatory)','Arduino / STM32','Digital electronics','UART, SPI, I2C'],tl:['Arduino IDE','Keil MDK','Proteus'],ent:[],ct:['NPTEL Embedded Systems (free)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['RTOS -- FreeRTOS','ESP32 + Raspberry Pi','Linux for embedded','MQTT for IoT'],tl:['FreeRTOS','KiCad (free PCB)','MQTT broker'],ent:['AWS IoT Core (free)','IBM Watson IoT'],ct:['AWS IoT Developer (free)'],role:'Embedded Engineer / IoT Dev',sal:'Rs4-8 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['AUTOSAR (automotive)','Yocto Linux','FPGA -- VHDL','CAN bus protocol'],tl:['Xilinx Vivado','MATLAB/Simulink','Vector CANalyzer'],ent:['AWS Greengrass edge','NI LabVIEW'],ct:['Certified Embedded Designer'],role:'Senior Embedded Engineer',sal:'Rs10-20 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['SoC architecture','Power optimisation','HW-SW co-design'],tl:['Synopsys','Cadence','ARM Dev Studio'],ent:['AWS SageMaker edge ML'],ct:['ARM Accredited Engineer'],role:'Embedded Architect / Principal',sal:'Rs25-55 LPA'},
    ],
    cos:[{t:'Automotive / EV',n:'Ather Energy, Ola Electric, Tata Motors, Bosch, Continental',s:'Rs6-14 LPA fresher'},{t:'Semiconductor',n:'Texas Instruments, Qualcomm, MediaTek, NXP, STMicro',s:'Rs8-18 LPA fresher'},{t:'IT services embedded',n:'Tata Elxsi, KPIT, HCL, L&T Technology',s:'Rs5-10 LPA fresher'}]},
  { id:'devops', branch:'IT', title:'DevOps / Cloud Engineer', tag:'Highest ROI skill in IT', demand:'60% of companies report an acute DevOps talent shortage',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Linux fundamentals (mandatory)','Networking -- TCP/IP, DNS','Python scripting','Bash scripting'],tl:['Ubuntu / WSL2','VS Code','GitHub'],ent:[],ct:['Linux Essentials (free)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Docker containerisation','AWS core (EC2, S3, VPC)','CI/CD with GitHub Actions','Terraform basics'],tl:['Docker Desktop','AWS Free Tier','GitHub Actions'],ent:['ServiceNow CSA (ITSM)','AWS CloudWatch'],ct:['AWS Cloud Practitioner','Terraform Associate'],role:'DevOps / Cloud Engineer',sal:'Rs6-12 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Kubernetes orchestration','Advanced Terraform','DevSecOps basics','SRE principles'],tl:['Kubernetes','Helm','ArgoCD','Datadog'],ent:['ServiceNow ITSM full','Boomi integration'],ct:['CKA -- Certified Kubernetes Admin'],role:'Senior DevOps / SRE',sal:'Rs14-25 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Platform engineering','FinOps -- cloud cost governance','Multi-region architecture'],tl:['Backstage','Crossplane','OPA'],ent:['AWS Bedrock (AI ops)','ServiceNow full suite'],ct:['AWS DevOps Professional','CKAD'],role:'DevOps Architect / Platform Lead',sal:'Rs28-60 LPA'},
    ],
    cos:[{t:'Cloud-native',n:'AWS India, Google Cloud, Microsoft Azure, Cloudflare',s:'Rs15-35 LPA fresher'},{t:'Product companies',n:'Razorpay, PhonePe, CRED, Swiggy, Zepto',s:'Rs12-22 LPA fresher'},{t:'IT services cloud',n:'Wipro AWS BU, TCS Cloud, Infosys Cloud',s:'Rs6-12 LPA fresher'}]},
  { id:'mech-d', branch:'MECH', title:'Product / Design Engineer', tag:'Build real things -- from concept to manufacturing', demand:'EV + manufacturing boom creating 40,000+ mechanical design roles',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Engineering drawing & GD&T','Statics + strength of materials','Thermodynamics','Material science'],tl:['AutoCAD 2D','SolidWorks basics','Ansys Student'],ent:[],ct:['SolidWorks CSWA (free for students)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['3D CAD -- SolidWorks advanced','FEA -- structural analysis','Thermal analysis','Manufacturing processes'],tl:['SolidWorks','Ansys Mechanical','MATLAB basics'],ent:['Ansys Student FEA','MATLAB academic'],ct:['SolidWorks CSWP','Ansys ACP'],role:'Design Engineer / Product Engineer',sal:'Rs3.5-7 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['CFD simulation','Design for Manufacturing (DFM)','FMEA & reliability','PLM basics'],tl:['Siemens NX','Ansys Fluent','Teamcenter PLM'],ent:['Siemens NX + Teamcenter PLM','Ansys CFD'],ct:['Ansys ACP','Siemens NX cert'],role:'Senior Design Engineer',sal:'Rs10-20 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Systems engineering','Architecture decisions','Team leadership','Supplier management'],tl:['Siemens NX advanced','PLM enterprise'],ent:['Siemens Teamcenter enterprise','MATLAB + Simulink advanced'],ct:['PE Certification'],role:'Principal Engineer / Technical Lead',sal:'Rs22-50 LPA'},
    ],
    cos:[{t:'Automotive / EV',n:'Ather Energy, Ola Electric, Tata Motors, Mahindra, Bosch',s:'Rs5-12 LPA fresher'},{t:'Aerospace / Defence',n:'HAL, ISRO, DRDO, Safran, Boeing India',s:'Rs6-14 LPA fresher'},{t:'Manufacturing MNCs',n:'L&T Engineering, Godrej, 3M India, Cummins',s:'Rs4-9 LPA fresher'}]},
  { id:'civil-s', branch:'CIVIL', title:'Structural / Infrastructure Engineer', tag:'Build the bridges, roads, and buildings of tomorrow', demand:'Smart cities and infra boom creating 60,000+ CIVIL roles by 2026',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Structural mechanics','Soil mechanics','Engineering materials','Surveying'],tl:['AutoCAD 2D','MS Excel for engineering'],ent:[],ct:['AutoCAD Certified User (free student)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['STAAD.Pro structural analysis','RCC & steel design (IS codes)','Quantity estimation','Project scheduling'],tl:['STAAD.Pro','Oracle Primavera P6','AutoCAD Civil 3D'],ent:['STAAD.Pro (Bentley student)','Oracle Primavera (trial)'],ct:['Bentley STAAD cert'],role:'Site / Junior Structural Engineer',sal:'Rs3-6 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['BIM -- Revit proficiency','GIS basics -- QGIS','ETABS advanced','Quality management'],tl:['Autodesk Revit','QGIS','ETABS','MS Project'],ent:['Autodesk Revit BIM','QGIS + ArcGIS','Oracle Primavera'],ct:['Revit Certified Professional'],role:'Structural Engineer / BIM Engineer',sal:'Rs8-18 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Project management (PMP)','Digital twin in construction','Advanced BIM coordination'],tl:['Navisworks BIM','Primavera Enterprise'],ent:['Autodesk Construction Cloud','Oracle Primavera Enterprise'],ct:['PMP Certification'],role:'Senior Engineer / Project Manager',sal:'Rs18-45 LPA'},
    ],
    cos:[{t:'EPC / Construction',n:'L&T Construction, Shapoorji, NCC Ltd, Afcons, HCC',s:'Rs3.5-7 LPA fresher'},{t:'Consultancy',n:'STUP Consultants, AECOM, Jacobs, Atkins, Mott MacDonald',s:'Rs4-8 LPA fresher'},{t:'Government / PSU',n:'NHAI, RITES, IRCON, CPWD, Smart City SPVs',s:'Rs5-10 LPA (GATE required)'}]},
  { id:'bca-w', branch:'BCA', title:'Full-Stack + Digital Marketing', tag:'Web development, digital marketing, and enterprise tools', demand:'High demand for web developers and digital analysts across all sectors',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1',sk:['HTML + CSS + JavaScript','Python basics','SQL basics','MS Office advanced'],tl:['VS Code','Chrome DevTools','WordPress basics'],ent:[],ct:['Google Digital Garage (free)'],role:'Building foundations',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 2-3',sk:['React.js or Node.js','WordPress + Shopify','Google Analytics 4','Database design basics'],tl:['WordPress','Shopify','Google Analytics','Canva Pro'],ent:['Google Analytics (free cert)','Salesforce Trailhead (free)'],ct:['Google Analytics GAIQ (free)','Shopify Partner cert (free)'],role:'Junior Web Developer / Digital Analyst',sal:'Rs2.5-5 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-2 years',sk:['Full-stack development','eCommerce management','SEO + SEM','Power BI dashboards'],tl:['React','Node.js','Power BI Desktop','Google Ads'],ent:['Power BI (free)','Google Ads certified','Salesforce Admin'],ct:['Google Ads Certification (free)','Microsoft PL-300'],role:'Web Developer / Digital Marketing Analyst',sal:'Rs5-12 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'3+ years',sk:['Technical SEO','eCommerce strategy','Team management','Data analytics'],tl:['GA4 advanced','Power BI enterprise','HubSpot'],ent:['Salesforce full platform','Power BI + Snowflake'],ct:['Salesforce Admin cert','HubSpot Marketing cert'],role:'Senior Developer / Digital Manager',sal:'Rs12-28 LPA'},
    ],
    cos:[{t:'Digital agencies',n:'Dentsu, Publicis, Ogilvy Digital, WATConsult, iProspect',s:'Rs3-6 LPA fresher'},{t:'eCommerce companies',n:'Myntra, Nykaa, Meesho, D2C startups, Amazon India',s:'Rs3-7 LPA fresher'},{t:'IT services',n:'TCS, Infosys, Wipro (junior roles), Capgemini',s:'Rs3.5-5.5 LPA fresher'}]},
  { id:'mca-e', branch:'MCA', title:'Enterprise Software Developer', tag:'High-paying MNC roles through enterprise platforms', demand:'MCA students with enterprise skills get 2x the average campus package',
    phases:[
      {n:1,nm:'Foundation',dr:'Sem 1-2',sk:['Java or Python (go deep)','SQL + DBMS fundamentals','OOP design patterns','Algorithms + data structures'],tl:['IntelliJ IDEA','MySQL Workbench','Git','VS Code'],ent:[],ct:['Oracle Java SE cert prep (free practice)'],role:'Building fundamentals',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Sem 3-4',sk:['Spring Boot (Java backend)','REST API development','Cloud basics -- AWS','ServiceNow CSA'],tl:['Spring Boot','Postman','AWS Free Tier','Docker basics'],ent:['ServiceNow CSA (free dev instance)','Salesforce Trailhead (free)'],ct:['AWS Cloud Practitioner','ServiceNow CSA'],role:'Software Developer / Enterprise Developer',sal:'Rs5-10 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-2 years',sk:['MuleSoft integration','Microservices architecture','CI/CD pipelines','System design basics'],tl:['Anypoint Platform','Kubernetes basics','GitHub Actions'],ent:['MuleSoft Certified Developer','Salesforce Developer I'],ct:['MuleSoft Level 1','AWS SA Associate'],role:'Senior Developer / Integration Specialist',sal:'Rs12-22 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'3+ years',sk:['Enterprise architecture','API strategy','Team leadership','Solution design'],tl:['MuleSoft Anypoint','Salesforce full stack','AWS enterprise'],ent:['MuleSoft Certified Architect','Salesforce Architect','Amazon Bedrock'],ct:['MuleSoft Architect cert','Salesforce Architect cert'],role:'Tech Lead / Solution Architect',sal:'Rs22-55 LPA'},
    ],
    cos:[{t:'IT services (premium roles)',n:'TCS iON, Infosys BPM, Capgemini, Deloitte USI, EY GDS',s:'Rs6-12 LPA fresher'},{t:'Product companies',n:'SAP Labs, Salesforce India, ServiceNow India, Oracle',s:'Rs10-22 LPA fresher'},{t:'MNC GCCs',n:'HSBC Tech, Standard Chartered Tech, JP Morgan Tech',s:'Rs8-18 LPA fresher'}]},
  { id:'mulesoft-dev', branch:'IT', title:'MuleSoft Integration SDE', tag:'Enterprise API plumbing and system connectivity', demand:'High demand across Banking & Global MNC GCCs',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['XML, JSON, & YAML basics','REST & SOAP API concepts','Core Java programming','HTTP and TCP/IP networks'],tl:['VS Code','Postman','Git & GitHub'],ent:['API specifications (RAML)'],ct:['MuleSoft Trailhead Integration Basics'],role:'Understanding Data Formats & Protocols',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Mule runtime architecture','Anypoint Studio basics','DataWeave transformations','API design with RAML'],tl:['Anypoint Studio','AnyPoint Platform','MUnit testing'],ent:['MuleSoft Integration'],ct:['MuleSoft Level 1'],role:'Associate Integration Developer',sal:'Rs6-10 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Advanced DataWeave','Error handling strategies','API gateway routing & policies','CloudHub deployment'],tl:['CloudHub','Anypoint Visualizer','AnyPoint Monitoring'],ent:['MuleSoft CloudHub','Salesforce connector'],ct:['MuleSoft Certified Integration Architect'],role:'Senior Integration Specialist',sal:'Rs15-25 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Enterprise integration patterns (EIP)','Clustering and high availability','CI/CD Mule Maven Plugin'],tl:['Mule Maven Plugin','Jenkins','Kubernetes'],ent:['MuleSoft Runtime Fabric'],ct:['MuleSoft Certified Platform Architect'],role:'Integration Architect / Principal SDE',sal:'Rs30-50 LPA'},
    ],
    cos:[{t:'Premium GCCs / Product',n:'Salesforce, MuleSoft India, Accenture AWS, Deloitte',s:'Rs10-22 LPA'},{t:'Large Integrators',n:'Capgemini, Infosys, Wipro, Cognizant, Hexaware',s:'Rs6-10 LPA'},{t:'Financial Institutions',n:'Standard Chartered, HSBC, JP Morgan Chase',s:'Rs8-15 LPA'}]},
  { id:'servicenow-dev', branch:'MCA', title:'ServiceNow Workflow Developer', tag:'Digitizing and automating enterprise business processes', demand:'Fastest-growing enterprise platform workflow roles',
    phases:[
      {n:1,nm:'Foundation',dr:'Sem 1-2',sk:['JavaScript (ES6+) fundamentals','Relational database concepts (SQL)','HTML & CSS basics','ITIL framework basics'],tl:['VS Code','Chrome DevTools','SQL Workbench'],ent:['ITIL foundations'],ct:['ITIL v4 Foundation Certificate'],role:'Learning Scripting & ITIL',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Sem 3-4',sk:['ServiceNow Administration','Business rules & Client scripts','UI Policies & Actions','Service Catalog items'],tl:['ServiceNow Personal Developer Instance (PDI)','ServiceNow Studio'],ent:['ServiceNow ITSM'],ct:['ServiceNow Certified System Administrator (CSA)'],role:'Junior ServiceNow Consultant',sal:'Rs6-12 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-2 years',sk:['Service Portal development','Integration Hub (REST APIs)','Flow Designer workflows','ServiceNow scripting (Glide API)'],tl:['ServiceNow Flow Designer','Integration Hub','Service Portal Builder'],ent:['ServiceNow Portal','IntegrationHub'],ct:['ServiceNow Certified Application Developer (CAD)'],role:'ServiceNow Developer',sal:'Rs12-22 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'3+ years',sk:['Domain separation','Custom application architecture','CMDB & Discovery orchestration','Performance analytics'],tl:['ServiceNow CMDB','Discovery Scheduler','Mid Server'],ent:['ServiceNow ITOM / HRSD'],ct:['ServiceNow Certified Implementation Specialist (CIS)'],role:'ServiceNow Solution Architect',sal:'Rs22-45 LPA'},
    ],
    cos:[{t:'Enterprise Partners',n:'Accenture, Deloitte, Capgemini, EY GDS, KPMG',s:'Rs8-15 LPA'},{t:'Product MNCs',n:'ServiceNow India, Salesforce, SAP Labs',s:'Rs12-25 LPA'},{t:'MNC GCCs',n:'Cognizant, Wipro ServiceNow Practice, DXC Technology',s:'Rs6-12 LPA'}]},
  { id:'bedrock-ai', branch:'CSE', title:'Amazon Bedrock GenAI Developer', tag:'Orchestrate LLMs and agentic workflows in the cloud', demand:'45% YoY increase in generative AI cloud roles',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Python programming (advanced)','REST APIs & JSON handling','Machine learning fundamentals','Prompt engineering principles'],tl:['Jupyter Notebooks','Postman','Git & GitHub'],ent:['Cloud fundamentals'],ct:['DeepLearning.AI Prompt Engineering Course'],role:'Understanding AI Model APIs',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Amazon Bedrock APIs','Claude, Llama, and Titan model features','LangChain orchestration framework','Retrieval-Augmented Generation (RAG)'],tl:['AWS Console','VS Code','Hugging Face'],ent:['Amazon Bedrock'],ct:['AWS Certified AI Practitioner'],role:'GenAI Developer Intern',sal:'Rs10-18 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Bedrock Knowledge Bases (Vector DBs)','Agentic workflows (Bedrock Agents)','Model fine-tuning on AWS','LLM guardrails and safety'],tl:['Pinecone / OpenSearch','LangGraph','AWS Lambda','AWS IAM'],ent:['Amazon Bedrock Agents','Amazon OpenSearch'],ct:['AWS Certified Machine Learning Specialty'],role:'GenAI Cloud Engineer',sal:'Rs20-35 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Enterprise GenAI systems design','AI cost optimization & rate-limiting','Multi-agent frameworks','Custom model hosting (SageMaker)'],tl:['AWS SageMaker','Bedrock Guardrails','LangSmith'],ent:['Amazon Bedrock Enterprise'],ct:['AWS Certified Solutions Architect Professional'],role:'Principal AI Solution Architect',sal:'Rs35-75 LPA'},
    ],
    cos:[{t:'Cloud Platforms & Tier 1',n:'Amazon, AWS India CoE, Microsoft AI, Google Cloud',s:'Rs25-55 LPA'},{t:'AI Consultancies / Startups',n:'Accenture GenAI Lab, Fractal Analytics, Quantiphi',s:'Rs14-30 LPA'},{t:'Enterprise SIs',n:'TCS AI CoE, Infosys Topaz, Wipro ai360',s:'Rs8-18 LPA'}]},
  { id:'vivado-fpga', branch:'ECE', title:'Xilinx FPGA Logic Designer', tag:'RTL design and hardware acceleration using Vivado', demand:'Semiconductor boom driving hardware/RTL jobs',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Digital design & Logic gates','Verilog or VHDL coding','FSM (Finite State Machines)','Computer architecture basics'],tl:['ModelSim','Digital Simulator','Proteus'],ent:['Digital Logic design'],ct:['NPTEL Digital Circuits Certification'],role:'Understanding Logic Synthesis',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Xilinx Vivado design flow','RTL synthesis and simulation','FPGA architecture (CLBs, DSPs, BRAM)','Timing constraints (XDC basics)'],tl:['Xilinx Vivado WebPACK','Basys 3 / Pynq FPGA boards'],ent:['Xilinx Vivado'],ct:['Xilinx Certified FPGA Associate'],role:'FPGA Verification Intern',sal:'Rs8-15 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Static Timing Analysis (STA)','AXI stream and bus interfaces','IP integrator block designs','High-Level Synthesis (HLS)'],tl:['Vivado Logic Analyzer (ILA)','Xilinx Vitis HLS','Oscilloscope'],ent:['Xilinx Vivado Design Suite','Vitis IDE'],ct:['Xilinx Certified FPGA Developer'],role:'FPGA Logic Designer',sal:'Rs15-28 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['SoC integration (Zynq UltraScale+)','Hardware acceleration architectures','Multi-gigabit transceivers','PCIe & Ethernet board design'],tl:['Vivado Enterprise','Mentor Graphics','Cadence Allegro'],ent:['Xilinx Zynq platform'],ct:['ARM Accredited Engineer / Custom chip specialist'],role:'Lead FPGA / RTL Architect',sal:'Rs30-55 LPA'},
    ],
    cos:[{t:'Semiconductor MNCs',n:'Qualcomm, MediaTek, NVIDIA, Intel, AMD, Samsung Sem.',s:'Rs15-35 LPA'},{t:'Defence & Aerospace CoE',n:'ISRO, DRDO, BEL, HAL, Mistral Solutions',s:'Rs8-16 LPA'},{t:'R&D Service Providers',n:'Tata Elxsi, Wipro VLSI Practice, Capgemini Engineering',s:'Rs6-12 LPA'}]},
  { id:'ansys-fea', branch:'MECH', title:'Ansys FEA Simulation Specialist', tag:'Validate stress, heat transfer, and fluids before prototyping', demand:'Mandatory skill in Aerospace, EV automotive, and Heavy Machinery',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Strength of materials (Solid Mechanics)','Heat and mass transfer','Fluid mechanics','Finite Element Method (FEM) theory'],tl:['AutoCAD 2D','MS Excel','Ansys Student Edition'],ent:['Structural Mechanics'],ct:['NPTEL Finite Element Method (free)'],role:'Understanding Stress & Strain Mechanics',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Ansys Workbench project flow','Static Structural FEA (1D, 2D, 3D)','Meshing and boundary conditions','Modal & Buckling analysis'],tl:['Ansys Mechanical','SpaceClaim geometry editor'],ent:['Ansys Simulation'],ct:['Ansys Certified Professional (ACP) - Structural'],role:'FEA Engineer Intern',sal:'Rs4-9 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Non-linear structural FEA (contacts & plasticity)','CFD simulations (Ansys Fluent)','Transient thermal analysis','Fatigue and durability analysis'],tl:['Ansys Fluent','Ansys LS-DYNA (crash test)','nCode DesignLife'],ent:['Ansys Workbench','Ansys Fluent'],ct:['Ansys Certified Professional (ACP) - Fluids/Explicit'],role:'Simulation / CAE Analyst',sal:'Rs10-20 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['Multi-physics coupled simulation (FSI)','Topology and shape optimization','Simulation data management (SPDM)','Validating FEA results with physical test data'],tl:['Ansys Discovery','Teamcenter Simulation','Ansys Minerva'],ent:['Ansys Enterprise Multi-physics'],ct:['NAFEMS Professional Simulation Engineer (PSE)'],role:'Lead Simulation / CAE Architect',sal:'Rs20-40 LPA'},
    ],
    cos:[{t:'Automotive / EV OEM',n:'Ather Energy, Ola Electric, Tata Motors, Mahindra, Maruti',s:'Rs6-14 LPA'},{t:'Aerospace & Defence',n:'HAL, ISRO, GE Aerospace, Boeing India, Rolls-Royce',s:'Rs8-18 LPA'},{t:'Engineering Services',n:'L&T Technology Services, Capgemini Engineering, Tata Elxsi',s:'Rs5-10 LPA'}]},
  { id:'revit-bim', branch:'CIVIL', title:'Autodesk Revit BIM Coordinator', tag:'Intelligent 3D building modeling for modern infrastructure', demand:'Mandatory for Indian infra projects above Rs100 Cr',
    phases:[
      {n:1,nm:'Foundation',dr:'Year 1-2',sk:['Building drawing & planning','Construction materials & methods','Basic structural engineering','AutoCAD 2D drafting'],tl:['AutoCAD 2D','MS Excel'],ent:['Building planning'],ct:['AutoCAD Certified User'],role:'Understanding Engineering Blueprints',sal:'--'},
      {n:2,nm:'Placement Ready',dr:'Year 3',sk:['Revit Architecture modeling','Revit Structure reinforcement modeling','Family creation (parametric objects)','BIM workflow standards'],tl:['Autodesk Revit','BIM 360 basics'],ent:['Autodesk Revit'],ct:['Autodesk Certified Professional: Revit for Structural Design'],role:'BIM Modeler Trainee',sal:'Rs3.5-7 LPA'},
      {n:3,nm:'Junior to Mid',dr:'0-3 years',sk:['Clash detection & coordination','Quantity takeoff & scheduling in Revit','Revit MEP modeling (HVAC, plumbing)','Shared coordinates and link management'],tl:['Autodesk Navisworks Manage','Revit MEP','BIM 360 Design'],ent:['Autodesk Revit BIM Suite','Navisworks'],ct:['Autodesk Certified Professional: Revit for Architectural Design'],role:'BIM Coordinator',sal:'Rs8-15 LPA'},
      {n:4,nm:'Senior & Beyond',dr:'4+ years',sk:['BIM Execution Plan (BEP) drafting','Common Data Environment (CDE) management','Point cloud to BIM modeling','4D (Time) & 5D (Cost) BIM integration'],tl:['Autodesk Construction Cloud','Synchro 4D','Revit Dynamo scripting'],ent:['Autodesk Construction Cloud Enterprise'],ct:['RICS Certificate in BIM / BIM Manager Certification'],role:'BIM Manager / Infrastructure Lead',sal:'Rs15-30 LPA'},
    ],
    cos:[{t:'Large EPC Developers',n:'L&T Construction, Shapoorji Pallonji, Afcons, Tata Projects',s:'Rs4-8 LPA'},{t:'Global Consultancies',n:'AECOM, Jacobs, Atkins, Mott MacDonald, WSP India',s:'Rs5-10 LPA'},{t:'Real Estate Giants',n:'DLF, Godrej Properties, Sobha, Lodha Group',s:'Rs4-7.5 LPA'}]},
]

export interface Comment { user:string; avatar:string; color:string; text:string }
export interface Post {
  id:number; user:string; branch:Branch; college:string; year:string
  avatar:string; color:string; content:string; tags:string[]
  likes:number; comments:Comment[]; time:string
}
export const POSTS: Post[] = [
  {id:1,user:'Arjun Mehta',branch:'CSE',college:'VIT Vellore',year:'3rd Year',avatar:'AM',color:'#818cf8',content:"Just passed my UiPath Certified Professional exam! Studied 6 weeks using Community Edition and free Academy modules. Already have interview calls from TCS Digital and Infosys BPM. Nobody in my college even knew about UiPath 3 months ago.",tags:['win','certification','UiPath'],likes:47,comments:[{user:'Priya S',avatar:'PS',color:'#f472b6',text:"Congratulations! Which modules did you focus on most?"},{user:'Rahul K',avatar:'RK',color:'#34d399',text:"Amazing! Starting my UiPath journey next week. Any tips?"}],time:'2h ago'},
  {id:2,user:'Sneha Reddy',branch:'CSE',college:'BITS Pilani',year:'4th Year',avatar:'SR',color:'#f472b6',content:"Hot take: MuleSoft is the most underrated skill for IT students. Everyone is learning React while MuleSoft Certified Developers get Rs15-18 LPA at 1 year experience. Anypoint trial is free. Trailhead courses are free. There is literally no excuse not to start.",tags:['opinion','MuleSoft'],likes:89,comments:[{user:'Dev P',avatar:'DP',color:'#60a5fa',text:"100% agree. Got Level 1 cert last month and already have a Deloitte offer."}],time:'4h ago'},
  {id:3,user:'Karthik N',branch:'ECE',college:'NIT Trichy',year:'3rd Year',avatar:'KN',color:'#fb923c',content:"ECE students -- stop ignoring AWS IoT Core. Built a smart home project with ESP32 + AWS IoT Core. Posted on GitHub. Now have internship offers from Ather Energy and a startup. The project cost Rs400 for the ESP32. The AWS part was free tier.",tags:['project','win'],likes:134,comments:[{user:'Meena R',avatar:'MR',color:'#fbbf24',text:"Can you share the GitHub link? Need this for placements."},{user:'Arun V',avatar:'AV',color:'#818cf8',text:"Ather Energy internship! Congrats!"}],time:'6h ago'},
  {id:4,user:'Priya Nair',branch:'MECH',college:'College of Engineering Trivandrum',year:'Final Year',avatar:'PN',color:'#fbbf24',content:"MECH students -- Ansys Student Edition is completely free. Did FEA simulations of a suspension component for 2 months, documented everything, posted on LinkedIn. Got interview calls from Tata Motors and KPIT. Your simulation portfolio is your resume.",tags:['project','win'],likes:78,comments:[{user:'Rohit S',avatar:'RS',color:'#fb923c',text:"Which Ansys module for the suspension analysis?"}],time:'1d ago'},
  {id:5,user:'Vishal Reddy',branch:'CIVIL',college:'Osmania University',year:'3rd Year',avatar:'VR',color:'#34d399',content:"CIVIL students -- get the Autodesk Revit student license today. It is free for 1 year. BIM is now mandatory on government projects above Rs100 crore. Spent 3 months learning it and my internship placement rate is completely different from classmates who only know AutoCAD.",tags:['opinion','certification'],likes:56,comments:[{user:'Anita K',avatar:'AK',color:'#0891b2',text:"How do you get the free student license?"}],time:'2d ago'},
]

export interface Message { me:boolean; text:string; time:string }
export interface Conversation {
  name:string; branch:Branch; color:string; avatar:string
  unread:boolean; preview:string; time:string; messages:Message[]
}
export const DMS: Conversation[] = [
  {name:'Sneha Reddy',branch:'CSE',color:'#f472b6',avatar:'SR',unread:true,preview:'Sure! The Anypoint trial...',time:'2m',messages:[{me:false,text:"Hey! Saw your post about MuleSoft. How did you get started?",time:'10:32 AM'},{me:true,text:"Started with free Trailhead courses and the 30-day Anypoint trial.",time:'10:35 AM'},{me:false,text:"Sure! The Anypoint trial gives you everything. Which module first?",time:'10:37 AM'}]},
  {name:'Karthik N',branch:'ECE',color:'#fb923c',avatar:'KN',unread:false,preview:'Here is the GitHub link!',time:'1h',messages:[{me:false,text:"Can you share your ESP32 + AWS IoT project GitHub link?",time:'Yesterday'},{me:true,text:"Sure! github.com/karthikn/smart-home-iot -- the README explains everything.",time:'Yesterday'},{me:false,text:"Here is the GitHub link!",time:'Yesterday'}]},
  {name:'Rahul Verma',branch:'IT',color:'#c084fc',avatar:'RV',unread:false,preview:'Good luck!',time:'2h',messages:[{me:true,text:"Preparing for ServiceNow CSA. Any advice?",time:'3h ago'},{me:false,text:"Focus on ITSM fundamentals and build 2 apps on your dev instance.",time:'2h ago'},{me:false,text:"Good luck!",time:'2h ago'}]},
]
